import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
const messages = {
  'zh-CN': { language:'语言', login:'登录', register:'注册账号', logout:'退出', dashboard:'工作台', documents:'资料中心', tasks:'共享询价任务', templates:'我的账号模板', excel:'Excel工具', accounts:'账号管理', database:'数据库', external:'外部接收箱', manager:'主管/经理', purchaser:'采购专员', overseas:'海外业务员', admin:'总经理', approval:'职位申请已提交，请等待负责人审核后登录。', chooseRole:'账号创建成功，请选择职位。', pending:'待审核', role:'职位', name:'姓名', account:'账号', password:'密码', submit:'提交', registerTitle:'员工注册', chooseRoleTitle:'选择职位' },
  'en-US': { language:'Language', login:'Sign in', register:'Create account', logout:'Sign out', dashboard:'Workspace', documents:'Documents', tasks:'Shared RFQ tasks', templates:'My templates', excel:'Excel tools', accounts:'Accounts', database:'Database', external:'External inbox', manager:'Supervisor / Manager', purchaser:'Purchasing specialist', overseas:'Overseas sales', admin:'General manager', approval:'Role request submitted. Please wait for approval.', chooseRole:'Account created. Please choose your role.', pending:'Pending approval', role:'Role', name:'Name', account:'Account', password:'Password', submit:'Submit', registerTitle:'Create account', chooseRoleTitle:'Choose your role' },
  'es-ES': { language:'Idioma', login:'Iniciar sesión', register:'Crear cuenta', logout:'Salir', dashboard:'Espacio de trabajo', documents:'Documentos', tasks:'Tareas RFQ compartidas', templates:'Mis plantillas', excel:'Herramientas Excel', accounts:'Cuentas', database:'Base de datos', external:'Bandeja externa', manager:'Supervisor / Gerente', purchaser:'Especialista de compras', overseas:'Ventas internacionales', admin:'Director general', approval:'Solicitud de rol enviada. Espere la aprobación.', chooseRole:'Cuenta creada. Elija su rol.', pending:'Pendiente de aprobación', role:'Rol', name:'Nombre', account:'Cuenta', password:'Contraseña', submit:'Enviar', registerTitle:'Crear cuenta', chooseRoleTitle:'Elija su rol' }
};
const LanguageContext = createContext(null);
export const languageOptions = [['zh-CN','中文'],['en-US','English'],['es-ES','Español']];
export function I18nProvider({ children }) { const [language,setLanguage] = useState(() => localStorage.getItem('latic-language') || 'zh-CN'); useEffect(() => { localStorage.setItem('latic-language', language); document.documentElement.lang = language; }, [language]); const value = useMemo(() => ({ language,setLanguage,t:key => messages[language]?.[key] || messages['zh-CN'][key] || key }), [language]); return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>; }
export function useI18n() { return useContext(LanguageContext) || { language:'zh-CN', setLanguage:()=>{}, t:key=>key }; }
